services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - /root/task/data/pgdata:/var/lib/postgresql/data
      - /root/task/init_database.sql:/docker-entrypoint-initdb.d/init_database.sql
    environment:
      - POSTGRES_DB=student_db
      - POSTGRES_USER=student_user
      - POSTGRES_PASSWORD=student_pass
  fastapi:
    build:
      context: /root/task
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    working_dir: /root/task
    volumes:
      - /root/task:/root/task
    ports:
      - '8000:8000'
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    networks:
      - backend
networks:
  backend:
    driver: bridge
